### ISSUE TITLE
Grunt version on devDependencies

### ISSUE THREAD

**Issue by giannisp** [richardbolt/grunt-filerev-assets#10]
At the moment if [grunt@1.0.x](https://www.npmjs.com/package/grunt) is an existing dependency on package.json, there's this npm (v3.8.5) warning:

`npm WARN grunt-filerev-assets@0.3.2 requires a peer of grunt@~0.4.1 but none was installed.`

Can you please consider updating the version to support 1.x?

**Comment by richardbolt** [comment]
I'd be happy to merge a PR for whatever it takes to fix that. the peerDependencies field is set to ">=0.4.1" which should support Grunt 1.x happily: https://github.com/richardbolt/grunt-filerev-assets/blob/master/package.json#L37

**Comment by giannisp** [comment]
Yes, but for some reason npm's warning is about the devDependency https://github.com/richardbolt/grunt-filerev-assets/blob/master/package.json#L34
